config/routes.rb
RCode::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  class OwnDomain
    def self.matches?(request)
      (request.domain.present? && request.domain != Rails.configuration.app_main_domain) || request.subdomain.present? && request.subdomain != "www" #{"snowboarding.by"}
    end
  end

  constraints(OwnDomain) do
    get '/' => 'pages#front'
    resources :pages
    resources :menus
    resources :catalogs do
      post :sort, on: :collection
    end
    resources :categories do
      post :sort, on: :collection
    end
    resources :catalog_items do
      post :sort, on: :collection
    end
    resources :menu_items do
      post :sort, on: :collection
    end
    match 'menu_items/change_menu/:id', to: 'menu_items#change_menu', via: :post
    resources :blogs, except: :show
    resources :posts, except: :show

    resources :up_files #, only: [:create]

    get "blog/:id", :to => "posts#show"
    get "blog", :to => "blogs#show"
  end

  root to: "welcome#index"

  resources :sites, path: '/admin/sites'
  get "admin/list_for_add_owner", to: "sub_owners#list_for_add_owner"
  get "admin/add_owner", to: "sub_owners#add_owner"

  resources :line_items
  resources :carts
  resources :orders

  get 'personal_orders', to: 'orders#personal_orders'

end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :integer          not null, primary key
#  site_id    :integer
#  menu_id    :integer
#  title      :string
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Blog < ActiveRecord::Base

  belongs_to :site
  belongs_to :menu
  has_many :posts, dependent: :destroy
  has_many :menu_items, dependent: :destroy

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :correct_user, :only => [:create, :edit , :update, :destroy]


  def show
    @blog = current_site.blogs.first
    @posts = @blog.posts.all.order("created_at DESC")
  end

  def new
    @blog = Blog.new
    @menu = Menu.find(params[:menu_id])
  end

  def create
    @blog = current_site.blogs.new(blog_params)
    @menu = Menu.find(params[:blog][:menu_id])
    respond_to do |format|
      if @blog.save
        @menu_item = MenuItem.create(link: "/blog", blog_id: @blog.id, menu_id: @blog.menu_id, title: @blog.title)
        format.html { redirect_to current_url, notice: 'Блог успешно создан!' }
      else
        format.html { render action: 'new', :menu_id => @menu.id }
      end
    end
  end


  def edit
    load_blog
    @menu = @blog.menu
  end

  def update
    load_blog
    if @blog.update(blog_params)
      @blog.menu_items.update_all(title: @blog.title)
      redirect_to "/blog"
    end

  end



  def destroy
    load_blog
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to current_url, notice: 'Блог успешно обновлен!'}
      format.json { head :no_content }
    end
  end


  private

    def load_blog
      @blog = current_site.blogs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :slug, :site_id, :menu_id)
    end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.slim
.blog_container.relative

  - if correct_view
      .un_header
        .un_header_in
          .title
            | Блог

          .un_right_btns
            = link_to '', new_post_path(:blog_id => @blog.id), class: "un_nav_btn un_btn_page", title: "Добавить пост"
            = link_to '', edit_blog_path(@blog), class: "un_nav_btn un_btn_config", title: "Редактировать блог"
            = link_to '', blog_path(@blog), method: :delete, data: { confirm: 'Точно точно?' }, class: "un_nav_btn un_btn_delete", title: "Удалить"


  h1 = @blog.title 


  - @posts.each do |post|
    .post
      = image_tag(post.post_img_url, class: "img-responsive") if post.post_img?
      h2 = post.title
      .date 
        strong = post.created_at.strftime("%d %b. %Y")
      

      = post.summary.html_safe

      = link_to 'continue reading →', post_path(post), class: "post_link pull-right", title: "Подробнее"

app/views/blogs/_form.html.slim
= form_for(@blog) do |f|

  -if @blog.errors.any?
    .error_explanation.bg-danger
      h2
        = pluralize(@blog.errors.count, "error")
        |  prohibited this page from being saved:
      - @blog.errors.full_messages.each do |msg|
        li = msg

  .col-md-5
    .field.form-group
      = f.label :title
      = f.text_field :title, :class => 'form-control'


    = f.hidden_field :menu_id, :value => @menu.id

    .actions
      = f.submit 'Сохранить', :class => 'btn btn-success'

app/views/blogs/edit.html.slim
= render 'layouts/home_button'
.container
  .row
    .col-md-12

      h2 Редактировать блог!
      = render 'form'

      / h4 имя меню
      / = @menu.title

app/views/blogs/new.html.slim
= render 'layouts/home_button'
.container
  .row
    .col-md-12

      h2 Добавить блог!
      = render 'form'

      / h4 имя меню
      / = @menu.title

app/views/blogs/show.html.slim
= render partial: "blog", layout: "/themes/#{current_site.theme}/main"