config/routes.rb
RCode::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  class OwnDomain
    def self.matches?(request)
      (request.domain.present? && request.domain != Rails.configuration.app_main_domain) || request.subdomain.present? && request.subdomain != "www" #{"snowboarding.by"}
    end
  end

  constraints(OwnDomain) do
    get '/' => 'pages#front'
    resources :pages
    resources :menus
    resources :catalogs do
      post :sort, on: :collection
    end
    resources :categories do
      post :sort, on: :collection
    end
    resources :catalog_items do
      post :sort, on: :collection
    end
    resources :menu_items do
      post :sort, on: :collection
    end
    match 'menu_items/change_menu/:id', to: 'menu_items#change_menu', via: :post
    resources :blogs, except: :show
    resources :posts, except: :show

    resources :up_files #, only: [:create]

    get "blog/:id", :to => "posts#show"
    get "blog", :to => "blogs#show"
  end

  root to: "welcome#index"

  resources :sites, path: '/admin/sites'
  get "admin/list_for_add_owner", to: "sub_owners#list_for_add_owner"
  get "admin/add_owner", to: "sub_owners#add_owner"

  resources :line_items
  resources :carts
  resources :orders

  get 'personal_orders', to: 'orders#personal_orders'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end  
end

app/views/welcome/index.html.slim
.col-md-4.col-md-offset-4 
  h1 FAST SITE GENERATOR
  HR


- if !user_signed_in?
  .col-md-4.col-md-offset-4
    h3 Sign in
    .panel.panel-default
      .panel-body

        = form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
          = f.label :login
          = f.text_field :login, :autofocus => true, class: "form-control"

          = f.label :password
          = f.password_field :password, class: "form-control"

          - if devise_mapping.rememberable?
            .checkbox
              label
                = f.check_box :remember_me
                | Запомнить меня

          = f.submit "Sign in", class: "btn btn-lg btn-primary pull-right"

    .panel.panel-default
      .panel-body
        = render "devise/shared/links"


- if user_signed_in?
  .col-md-4.col-md-offset-4 
    = link_to 'New Site', new_site_path, class: "btn btn-large btn-primary"

.panel.panel-default
  .panel-body  
    p = request.subdomain
    p = request.domain