config/routes.rb
RCode::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  class OwnDomain
    def self.matches?(request)
      (request.domain.present? && request.domain != Rails.configuration.app_main_domain) || request.subdomain.present? && request.subdomain != "www" #{"snowboarding.by"}
    end
  end

  constraints(OwnDomain) do
    get '/' => 'pages#front'
    resources :pages
    resources :menus
    resources :catalogs do
      post :sort, on: :collection
    end
    resources :categories do
      post :sort, on: :collection
    end
    resources :catalog_items do
      post :sort, on: :collection
    end
    resources :menu_items do
      post :sort, on: :collection
    end
    match 'menu_items/change_menu/:id', to: 'menu_items#change_menu', via: :post
    resources :blogs, except: :show
    resources :posts, except: :show

    resources :up_files #, only: [:create]

    get "blog/:id", :to => "posts#show"
    get "blog", :to => "blogs#show"
  end

  root to: "welcome#index"

  resources :sites, path: '/admin/sites'
  get "admin/list_for_add_owner", to: "sub_owners#list_for_add_owner"
  get "admin/add_owner", to: "sub_owners#add_owner"

  resources :line_items
  resources :carts
  resources :orders

  get 'personal_orders', to: 'orders#personal_orders'

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_catalog_item(catalog_item_id, currency)
		current_item = line_items.find_by_catalog_item_id(catalog_item_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(catalog_item_id: catalog_item_id, currency: currency)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/controllers/carts_controller.rb
#encoding: UTF-8
class CartsController < ApplicationController
before_action :shop_activate?, only: :show

  def show
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path,
          notice: 'Корзина пуста' }
      format.json { head :ok }
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.slim
/encoding: UTF-8
h2 Корзина
br

table.table
  - if @cart.line_items.any?
    - @cart.line_items.each do |item|
      tr
        td
          .img
            = link_to image_tag(item.catalog_item.catalog_item_img_url(:thumb_60x60), :alt => item.catalog_item.title, :title => item.catalog_item.title), catalog_item_path(item.catalog_item), :class => 'noclass'
        td
          = item.quantity
          |&times;
          = item.catalog_item.title
          |&nbsp
          = item.total_price
          |&nbsp
          = item.currency
  - else
   h2 Ваша корзина пуста


h4
  | Общая стоимость 
  strong
    = @cart.total_price
    / = @cart.line_items.first.currency
.pull-right
  .btn-group role="group"
    = link_to 'Очистить корзину', @cart, method: :delete, data: {confirm: 'Вы уверены? Действие необратимо'}, class: "btn btn-default"
    = link_to 'Оформить заказ', new_order_path, method: :get, class: "btn btn-default"
    = link_to 'Назад', request.referer, class: "btn btn-default"

app/views/carts/show.html.slim
= render partial: "cart", layout: "/themes/#{current_site.theme}/main"