config/routes.rb
RCode::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  class OwnDomain
    def self.matches?(request)
      (request.domain.present? && request.domain != Rails.configuration.app_main_domain) || request.subdomain.present? && request.subdomain != "www" #{"snowboarding.by"}
    end
  end

  constraints(OwnDomain) do
    get '/' => 'pages#front'
    resources :pages
    resources :menus
    resources :catalogs do
      post :sort, on: :collection
    end
    resources :categories do
      post :sort, on: :collection
    end
    resources :catalog_items do
      post :sort, on: :collection
    end
    resources :menu_items do
      post :sort, on: :collection
    end
    match 'menu_items/change_menu/:id', to: 'menu_items#change_menu', via: :post
    resources :blogs, except: :show
    resources :posts, except: :show

    resources :up_files #, only: [:create]

    get "blog/:id", :to => "posts#show"
    get "blog", :to => "blogs#show"
  end

  root to: "welcome#index"

  resources :sites, path: '/admin/sites'
  get "admin/list_for_add_owner", to: "sub_owners#list_for_add_owner"
  get "admin/add_owner", to: "sub_owners#add_owner"

  resources :line_items
  resources :carts
  resources :orders

  get 'personal_orders', to: 'orders#personal_orders'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id           :integer          not null, primary key
#  catalog_id   :integer
#  site_id      :integer
#  title        :string
#  category_img :string
#  slug         :string
#  weight       :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Category < ActiveRecord::Base

  validates_presence_of :title

  belongs_to :catalog
  belongs_to :site
  has_many :catalog_items, dependent: :destroy

  mount_uploader :category_img, CategoryImgUploader

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  extend FriendlyId
  # friendly_id :slug_candidates, use: :slugged
  friendly_id :slug_candidates, :use => :scoped, :scope => :site


  def slug_candidates
    [
      :title,
      [:title, Random.rand(1..10)],
      [:title, Random.rand(10..99)]
    ]
  end

  def recreate_category_v
    Category.find_each do |user|
      user.category_img.recreate_versions! if user.category_img?
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :correct_user, :only => [:destroy, :edit , :update, :sort]

  def show
    load_category
  end

  def new
    @category = Category.new
    @catalog = Catalog.find(params[:catalog_id])
  end


  def create
    @category = current_site.categories.new(category_params)
    # passing catalog_id in _form view - no any magick hire! 

    respond_to do |format|
      if @category.save
        format.html { redirect_to current_url, notice: 'Category was successfully created.' }
      else
        flash[:error] = "there was a problem"
      end
    end
  end

  def edit
    load_category
  end

  def update
    load_category
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to current_url, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    load_category
    @menu = @category.catalog.menu
    @redirect_url = params[:redirectto]

    @category.destroy

    respond_to do |format|
      if @redirect_url == "1"
        format.html { redirect_to current_url.to_s, notice: 'Category was successfully deleted!'}
      else
        format.html { redirect_to menu_url(@menu), notice: 'Category was successfully deleted!'}
      end
    end
  end


  def sort
    params[:category].each_with_index do |id, index|
      Category.where(id: id).update_all(weight: index+1)
    end
    render nothing: true
  end

  private

    def load_category
      @category = current_site.categories.friendly.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :catalog_id, :site_id, :weight, :slug, :category_img, :category_img_cache)
    end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.slim
.category_page_category
  
  - if correct_view
    .un_header
      .un_header_in

        span
          .title
            | Раздел каталога

        .un_right_btns
          = link_to '', new_catalog_item_path(:category_id => @category.id), class: "un_nav_btn un_btn_plus", title: "Добавить товар"
          = link_to '', edit_category_path(@category), class: "un_nav_btn un_btn_config", title: "Редактировать раздел"
          = link_to '', category_path(@category), method: :delete, data: { confirm: 'Точно точно?' }, class: "un_nav_btn un_btn_delete", title: "Удалить"

  h1 = @category.title


  .clearfix
    .row
      .category_catalog_items.clearfix data-update-url=sort_catalog_items_url
        - @category.catalog_items.order("weight").each do |item|
          = content_tag_for :div, item, class: "catalog_item col-md-4 col-lg-3"

            - if correct_view
              .un_header_container
                .un_header
                  .un_header_in
                    .un_left_move
                    span
                      .title Товар
                    .un_right_btns
                      = link_to '', edit_catalog_item_path(item), class: "un_nav_btn un_btn_config", title: "Редактировать товар"
                      = link_to '', catalog_item_path, method: :delete, data: { confirm: 'Точно точно?' }, class: "un_nav_btn un_btn_delete", title: "Удалить"



            .img
              = link_to image_tag(item.catalog_item_img_url(:thumb_263x263), :alt => item.title, :title => item.title), catalog_item_path(item), :class => 'noclass'
            .title = link_to item.title, catalog_item_path(item)
            .price 
              = item.price if item.price
              |  
              = current_site.currency

            - if current_site.shop_active
            	= button_to 'Добавить в корзину', line_items_path(catalog_item_id: item), remote: true, class: "btn btn-default"

app/views/categories/_form.html.slim
= form_for(@category) do |f|
  .field.form-group
    = f.label :title
    = f.text_field :title, :class => 'form-control'

  / fieldset.image
  /   legend Картинка категории
  /   p
  /     = image_tag(@category.category_img_url) if @category.category_img?
  /     - unless @category.new_record?
  /       = f.check_box :remove_category_img
  /       = f.label :remove_category_img, "Удалить картинку"

  /   p
  /     = f.label :category_img, "Загрузить картинку:"
  /     = f.file_field :category_img
  /     = f.hidden_field :category_img_cache


  fieldset.image
    legend Картинка категории
    .form-group
      = f.label :category_img, "Загрузить картинку:"
      = f.file_field :category_img
      = f.hidden_field :category_img_cache
    .form-group
      = image_tag(@category.category_img_url(:thumb_263x263)) if @category.category_img?
    .form-group
      - unless @category.new_record?
        .checkbox
          = content_tag :label
            = f.check_box :remove_category_img
            = label :remove_category_img, "Удалить картинку"
      


  hr

  
  = f.hidden_field :catalog_id, :value => @catalog.id if !@category.catalog_id?

  .actions
    .form-group
      = f.submit 'Сохранить', :class => 'btn btn-lg btn-success pull-right'

app/views/categories/edit.html.slim
= render 'layouts/home_button'
.container
  .row
    .col-md-12
      h2 Редактировать категорию!
      = render 'form'
      h4 имя каталога
      = @category.catalog.title 

app/views/categories/new.html.slim
= render 'layouts/home_button'
.container
  .row
    .col-md-12
      h2 Добавить категорию в каталог!
      br
      = render 'form'

app/views/categories/show.html.slim
= render partial: "category", layout: "/themes/#{current_site.theme}/main"